#!/bin/sh
## Script called up strongswan to bring the vti interface up/down based on the state of the IPSec tunnel.
## Called as vti_up_down vti_intf_name

source /etc/default/vyatta
source /etc/default/locale
case "$PLUTO_VERB" in
route-client | up-client)
/opt/vyatta/sbin/vyatta-vti-config.pl --updown --intf=$1 --action=up
sudo /sbin/ip link set $1 up
sudo /sbin/ip route flush table 220
    ;;
down-client)
/opt/vyatta/sbin/vyatta-vti-config.pl --updown --intf=$1 --action=down 
    ;;
*)
    ;;
esac

sysctl -w net.ipv4.ip_forward=1
exit 0
